source 'https://rubygems.org/'

gem 'sinatra', '1.4.6'
gem 'sinatra-contrib'
gem 'slack-api', '1.1.6'
gem 'dotenv'
gem 'slim'
gem 'compass'
gem 'coffee-script'
gem 'minitest-power_assert'
gem 'simplecov'
